### ISSUE TITLE
Cannot write points in async mode.

### ISSUE THREAD

**Issue by jeremyd** [influxdb/influxdb-ruby#103]
For some reason I'm getting this when attempting to use async mode.
Using latest client and Influxdb 0.9.2
```
Cannot write data: #<ArgumentError: wrong number of arguments (1 for 2)>
```
I looked through this rescue block and I'm unsure why there aren't enough arguments here.

**Comment by toddboom** [comment]
@jeremyd i think this might have just been fixed with a PR - see if you can test it out with master, and i'll cut a new gem in just a bit!

**Comment by toddboom** [comment]
@jeremyd ok, `v0.2.2` is out now - let me know if that doesn't fix the problem!
