### ISSUE TITLE
0.9 and tags

### ISSUE THREAD

**Issue by SebastianSzturo** [influxdb/influxdb-ruby#77]
Is there anything in the works for 0.9 or are you looking for pull requests?

**Comment by adampats** [comment]
Bump.  We are also wondering about compatibility with 0.9 once it's released.  Not sure if we should try to refactor this gem ourselves or if someone smarter is already working on it.

**Comment by khangtoh** [comment]
we are having issue with 0.9 and the ruby client so any updates to support 0.9 will be nice.

**Comment by cjs226span** [comment]
Same here.

**Comment by bkdspanning** [comment]
+1

**Comment by chrishiestand** [comment]
+1

**Comment by n1tr0g** [comment]
:+1:

**Comment by n1tr0g** [comment]
@toddboom and/or @pauldix for now a branch would be enough, so people can start working on it :) #86

**Comment by 9mm** [comment]
+1

**Comment by robsonpeixoto** [comment]
:+1:

**Comment by pauldix** [comment]
We haven't started work on it, but we'd happily accept PRs! Still putting all our focus on the core DB, then docs, then libraries (in that order) :)

**Comment by n1tr0g** [comment]
But to start working on it wouldn't you first create an branch or you want us to commit potential breaking changes to the master ?

**Comment by pauldix** [comment]
gem versioning should take care of that. Besides, 0.8 is deprecated
anyway.  Basically, create a branch, do the work, issue a PR, and we should
be good to go.

**Comment by jsvisa** [comment]
If someone have done this? Currently I'm working on it, you will watch the branch [here](https://github.com/jsvisa/influxdb-ruby/tree/0.9), after I finish it, I'll send a PR.

**Comment by toddboom** [comment]
@jsvisa I'm working on this also, and am planning to have something released later today. Also, be aware of #88 which has some significant refactoring. i'm going to try to get that in place today.

I also released `v0.1.9` over the weekend, which will be the final release supporting InfluxDB v0.8.x. The `v0.2.0` release will not be backwards compatible.

**Comment by jsvisa** [comment]
@toddboom :+1: look forward to it

**Comment by kri5** [comment]
:+1:

**Comment by jacekgrzybowski** [comment]
I also started working on it ([my fork](https://github.com/efigence/influxdb-ruby/tree/0.9)). Client seems to be working properly (administration methods, querying, writing data using new api). @toddboom please let me know, if it might be any use. Also - I started working on it on friday, before the release of `0.1.9` and those changes have not been merged, however I'm willing to do it.

**Comment by mcastilho** [comment]
Can this be closed since #92 was merged ?

**Comment by toddboom** [comment]
@mcastilho yes - thanks!
