### ISSUE TITLE
new branch for influxdb 0.9.0

### ISSUE THREAD

**Issue by n1tr0g** [influxdb/influxdb-ruby#86]
Should you create a new branch for the upcoming influxDB 0.9.0 ? 

Would be good to start implementing the new features and API changes.

**Comment by chrishiestand** [comment]
+1

**Comment by chrishiestand** [comment]
duplicate of https://github.com/influxdb/influxdb-ruby/issues/77

**Comment by toddboom** [comment]
@n1tr0g we're working on it. should be out later today!
