### ISSUE TITLE
InfluxDB::Error: 404 page not found

### ISSUE THREAD

**Issue by gavinzhou** [influxdb/influxdb-ruby#89]
[root@ecLog01 ~]# irb
irb(main):001:0>
irb(main):002:0* require 'influxdb'
=> true
irb(main):003:0>
irb(main):004:0* InfluxDB::VERSION
=> "0.1.9"
irb(main):005:0>
irb(main):006:0* influxdb = InfluxDB::Client.new
=> #<InfluxDB::Client:0x00000001f8e598 @hosts=["localhost"], @port=8086, @path="", @username="root", @password="root", @auth_method="params", @use_ssl=false, @verify_ssl=true, @ssl_ca_cert=false, @time_precision="s", @initial_delay=0.01, @max_delay=30, @open_timeout=5, 
@read_timeout=300, @async=false, @retry=-1, @udp_client=nil>
irb(main):007:0>
irb(main):008:0* database = 'site_development'
=> "site_development"
irb(main):009:0>
irb(main):010:0* influxdb.create_database(database)
InfluxDB::Error: 404 page not found

	from /usr/local/share/ruby/gems/2.0/gems/influxdb-0.1.9/lib/influxdb/client.rb:384:in `block in post'
	from /usr/local/share/ruby/gems/2.0/gems/influxdb-0.1.9/lib/influxdb/client.rb:431:in `call'
	from /usr/local/share/ruby/gems/2.0/gems/influxdb-0.1.9/lib/influxdb/client.rb:431:in `connect_with_retry'
	from /usr/local/share/ruby/gems/2.0/gems/influxdb-0.1.9/lib/influxdb/client.rb:375:in `post'
	from /usr/local/share/ruby/gems/2.0/gems/influxdb-0.1.9/lib/influxdb/client.rb:94:in `create_database'
	from (irb):10
	from /usr/bin/irb:12:in `<main>'

**Comment by gavinzhou** [comment]
[root@ecLog01 ~]# influx
Connected to http://localhost:8086 version 0.9.1
InfluxDB shell 0.9.1
>

**Comment by toddboom** [comment]
@gavinzhou This gem doesn't yet support InfluxDB v0.9.x - keep an eye out for gem `v0.2.0`, which should be available later today.
