### ISSUE TITLE
Premature Update of README?

### ISSUE THREAD

**Issue by jonmchan** [influxdb/influxdb-ruby#93]
The README states that it is only compatible with 0.9.x, but I have tried writing data with the influxdb-ruby master branch library to influxdb 0.9.1 and I get errors. It would seem that influxdb-ruby is still incompatible with 0.9.0.

Can we keep the README as stating it is compatible with 0.8.x until we have verified that 0.9.x actually works? https://github.com/influxdb/influxdb-ruby/pull/92 would seem to actually need to be merged before we can work with 0.9.x.

It would be useful to remove this line: "If you're reading this message, then you should only expect support for InfluxDB v0.9.0 and higher."

**Comment by toddboom** [comment]
@jonmchan this was premature, but #92 is now merged in.
