### ISSUE TITLE
Add remark which versions of InfluxDB are supported

### ISSUE THREAD

**Issue by tisba** [influxdb/influxdb-ruby#97]
Since a lot has changed between InfluxDB 0.8.x and 0.9, it would be great to have a note/warning in README.md that states, what versions of this gem is considered compatible which what version of InfluxDB.

**Comment by radenui** [comment]
+1: is the current version usable with a 0.8.8 version ?
Otherwise, is there a tag I can refer to ?

Thanks!

**Comment by imrichardcole** [comment]
Does this version work with 0.8.x?

**Comment by jacekgrzybowski** [comment]
For influx 0.8.x use v0.1.9.

For influx 0.9.x use v0.2.0.

**Comment by rzane** [comment]
+1 Wish I saw this before spending an hour debugging!

**Comment by toddboom** [comment]
Sorry about this, guys. I had added a warning to the README a while back and it looks like it got yanked during a PR adding some v0.9.x features. I've put it back, so hopefully that will alleviate confusion going forward.
